### ISSUE TITLE
可能是图像文件路径出错

### ISSUE THREAD

**Issue by size404** [Cokene/Auto-Girls-Frontline#2]
运行报错
[ WARN:0@0.358] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:/Users/shliz/Desktop/Auto_GirlsFrontline/auto13_4/initial_IMG/map.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "D:\Auto-Girls-Frontline-master\auto13_4\auto13_4.py", line 896, in <module>
    if isInMap():
  File "D:\Auto-Girls-Frontline-master\auto13_4\auto13_4.py", line 331, in isInMap
    return imageCompare(initImage, capImage)
  File "D:\Auto-Girls-Frontline-master\auto13_4\auto13_4.py", line 306, in imageCompare
    gray_img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)  # ground_truth img
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by size404** [comment]
电脑小白，如果是我的问题还请多多指正

**Comment by Cokene** [comment]
大致清楚了，可以参考autoo13_4.py中code : 28行，该路径为存储图像的文件路径，将此项参数修改为你存储检测图像的位置。
不同账号的人形数量可能不同，请注意code : 85/95 行的两只人形位置是否合适。
（主要是我懒得练两只vector了， 2333）

**Comment by Cokene** [comment]
auto13_4.py为老版本的代码，新版代码已整合至autoIntegrationEdition文件夹中。

**Comment by webbrain-one** [comment]
Hi! I opened PR #7 to fix this — it corrects the `initial_IMG/map.png` path handling so OpenCV can find and read the image, preventing the `imread`/`cvtColor` error.
